name: Deploy to Azure Spring Apps

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: List target directory
      run: ls -la target

    - name: Deploy to Azure Spring Apps
      uses: azure/spring-apps-deploy@v1
      with:
        azure-subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        service-name: 'workshop-unit-test'
        app-name: 'workshop-unit-test-app'
        package: '${{ github.workspace }}/target/workshop-unit-test-0.0.1-SNAPSHOT.jar'
        deployment-type: 'development'
