name: Deploy to Azure Spring Apps

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Build Java application
      run: mvn clean package

    - name: List target directory
      run: ls -la target

    - name: Git Metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          noriegadocker/workshop-unit-test
        flavor: |
          latest=true
          prefix=
          suffix=
        tags: |
          type=edge,branch=master
          type=raw,value=buster-slim
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha,prefix=,format=long

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/workshop-unit-test:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Spring Apps
      run: |
        az spring app deploy --name workshop-unit-test-app --service workshop-unit-test --resource-group workshop-unit-test-app-rg --container-image noriegadocker/workshop-unit-test:latest
