name: Trigger auto deployment for workshop-devops

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/workshop-devops-AutoDeployTrigger-2990a4dc-578c-4c43-a170-2d77bc27c306.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Build Java application
      run: mvn clean package

    - name: List target directory
      run: ls -la target

    - name: Git Metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          noriegadocker/workshop-unit-test
        flavor: |
          latest=true
          prefix=
          suffix=
        tags: |
          type=edge,branch=master
          type=raw,value=buster-slim
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha,prefix=,format=long

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/workshop-unit-test:latest
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy image 
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: workshop-app-container
          resourceGroup: workshop-rg
          imageToDeploy: hub.docker.com/r/noriegadocker/workshop-devops:latest

